# Generated by Django 3.1.2 on 2020-11-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201110_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('slots', models.IntegerField()),
                ('speakers', models.ManyToManyField(blank=True, to='core.Speaker')),
            ],
            options={
                'verbose_name': 'talk',
                'verbose_name_plural': 'talks',
                'abstract': False,
            },
        ),
    ]
