# Generated by Django 3.1.2 on 2020-11-11 17:07

from django.db import migrations


class Migration(migrations.Migration):

    #atomic = False
    dependencies = [
        ('core', '0007_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='CourseOld',
        ),
        migrations.AlterModelOptions(
            name='courseold',
            options={'verbose_name': 'course',
                     'verbose_name_plural': 'courses'},
        ),
    ]
